### GET Bears HTML
GET localhost:5678/bears

### GET Bears JSON
GET localhost:5678/api/bears

### GET /kaboom Raise Exception
GET localhost:5678/kaboom

### hibernating 10s
GET localhost:5678/hibernate/10000
